In [1]:
import numpy as np
import gdal
import os
import geopandas as gpd

In [2]:
img_centroids_path = os.path.join("Bathinda", "Wheat_points_Bathinda.shp")

img_plots_points = gpd.read_file(img_centroids_path)

type(img_plots_points)

geopandas.geodataframe.GeoDataFrame

In [3]:
img_plots_points

class                   geometry
0        1  POINT (75.07613 30.41867)
1        1  POINT (75.07975 30.41471)
2        1  POINT (75.06798 30.41998)
3        1  POINT (75.06144 30.41724)
4        1  POINT (75.07176 30.42369)
..     ...                        ...
156      2  POINT (75.07848 30.36952)
157      2  POINT (74.73571 30.05672)
158      2  POINT (75.11021 30.08836)
159      2  POINT (74.89842 30.29340)
160      2  POINT (74.87244 30.35578)

[161 rows x 2 columns]

In [4]:
x = []
y = []
for p in img_plots_points['geometry']:
    x.append(np.array(p)[0])
    y.append(np.array(p)[1])

In [5]:
x = np.array(x)
y = np.array(y)

In [6]:
#x co-ordinates
print(x)

[75.07612828 75.07974629 75.06798021 75.06143562 75.07175676 75.07438827
 75.0854083  75.12549124 75.13729296 75.14777785 75.15432244 75.13462085
 75.148645   75.1524477  75.13214377 75.12655189 75.14571626 75.06786783
 75.11499857 75.12510397 75.11278726 75.06576716 75.07013379 75.04178312
 75.03973694 75.07069618 75.11844455 75.11209307 75.1416498  75.14201956
 75.26636546 75.26175206 75.27785076 75.28424514 75.27883781 75.29956592
 75.26888145 75.27424587 75.29364419 75.26175809 75.31632495 75.31761241
 75.33231092 75.31342817 75.33445669 75.18501573 75.19720369 75.08106879
 74.74553314 74.71394744 74.70965805 74.73676737 74.74389132 74.75035008
 74.73404332 75.07185722 75.13484162 75.1584648  75.19657834 75.22835605
 74.83280592 74.81250696 74.87688564 74.87879028 75.15836532 75.15847351
 75.15785123 75.1581731  75.15778686 75.13991479 75.157338   75.17398395
 75.16469768 75.1527243  75.14641575 75.06696661 75.12401974 75.13552105
 75.10338846 75.1193104  75.10999777 75.075408   75

In [7]:
#y co-ordinates
print(y)

[30.41866817 30.41470938 30.41997804 30.41723945 30.42368798 30.43512368
 30.42797265 30.56776762 30.5698184  30.57496276 30.57359565 30.51284876
 30.53219769 30.54168023 30.54206805 30.50644521 30.5260712  30.49846306
 30.47542181 30.45803108 30.5006103  30.4587298  30.46945712 30.4498275
 30.42829542 30.40638966 30.39337589 30.4020006  30.39228053 30.4150947
 30.29307663 30.2920576  30.29216451 30.2917569  30.28108767 30.27723335
 30.26730036 30.25641604 30.25227972 30.24227006 30.259082   30.26325211
 30.27300019 30.28448908 30.27122115 30.43062649 30.43243964 30.36865199
 30.06841389 30.0738362  30.05745694 30.05842213 30.05653706 30.05882142
 30.08961565 30.08528457 30.08603754 30.07967108 30.06658137 30.1753812
 30.3051298  30.3094832  30.29806411 30.34981265 30.53609741 30.52198427
 30.52203972 30.52329665 30.52331513 30.51473526 30.50184013 30.49477738
 30.49280587 30.5523252  30.55291652 30.50769677 30.4693611  30.46037242
 30.45863377 30.44641456 30.45466465 30.50268099 30.46

In [8]:
#function to get pixel indices from co-ordinates
def get_indices(x, y, ox, oy, pw, ph):
    """
    Gets the row (i) and column (j) indices in an array for a given set of coordinates.
    Based on x

    :param x:   array of x coordinates (longitude)
    :param y:   array of y coordinates (latitude)
    :param ox:  raster x origin
    :param oy:  raster y origin
    :param pw:  raster pixel width
    :param ph:  raster pixel height
    :return:    row (i) and column (j) indices
    """

    i = np.floor((oy-y) / ph).astype('int')
    j = np.floor((x-ox) / pw).astype('int')

    return i, j

In [15]:
ds = gdal.Open('E:\\Internship_Harvesting\\Dataset\\03_2020.tif')
xmin, xres, xskew, ymax, yskew, yres = ds.GetGeoTransform()
del ds

# calculate indices and index array
indices = get_indices(x, y, xmin, ymax, xres, -yres)

In [16]:
print(indices)

(array([1819, 1864, 1805, 1835, 1764, 1636, 1716,  160,  137,   80,   95,
        771,  556,  450,  446,  842,  624,  931, 1188, 1381,  907, 1373,
       1254, 1473, 1712, 1956, 2101, 2005, 2113, 1859, 3218, 3229, 3228,
       3232, 3351, 3394, 3504, 3626, 3672, 3783, 3596, 3550, 3441, 3313,
       3461, 1686, 1666, 2376, 5718, 5658, 5840, 5830, 5851, 5825, 5482,
       5531, 5522, 5593, 5739, 4528, 3083, 3035, 3162, 2586,  512,  669,
        669,  655,  655,  750,  894,  972,  994,  332,  325,  828, 1255,
       1355, 1375, 1511, 1419,  884, 1307, 1383, 1556, 1988, 1989, 2034,
       2049, 2011, 1943, 1981, 1928, 1996, 2028, 1896, 1887, 2149, 2126,
       2183, 2247, 2215, 2139, 2037, 2039, 2116, 2189, 1958, 1986, 3229,
       3250, 3238, 3291, 3312, 3302, 3253, 3228, 3172, 3292, 3268, 3282,
       3303, 3257, 3411, 3389, 3345, 3418, 3363, 3365, 3348, 3485, 3502,
       3496, 3467, 3459, 3525, 3425, 3477, 3425, 3454, 3382, 3393, 3360,
       3317, 3337, 3329, 3327, 3542, 3537, 3607, 3

In [17]:
pixels_x = indices[0]
pixels_y = indices[1]

In [18]:
#x indices
pixels_x

array([1819, 1864, 1805, 1835, 1764, 1636, 1716,  160,  137,   80,   95,
        771,  556,  450,  446,  842,  624,  931, 1188, 1381,  907, 1373,
       1254, 1473, 1712, 1956, 2101, 2005, 2113, 1859, 3218, 3229, 3228,
       3232, 3351, 3394, 3504, 3626, 3672, 3783, 3596, 3550, 3441, 3313,
       3461, 1686, 1666, 2376, 5718, 5658, 5840, 5830, 5851, 5825, 5482,
       5531, 5522, 5593, 5739, 4528, 3083, 3035, 3162, 2586,  512,  669,
        669,  655,  655,  750,  894,  972,  994,  332,  325,  828, 1255,
       1355, 1375, 1511, 1419,  884, 1307, 1383, 1556, 1988, 1989, 2034,
       2049, 2011, 1943, 1981, 1928, 1996, 2028, 1896, 1887, 2149, 2126,
       2183, 2247, 2215, 2139, 2037, 2039, 2116, 2189, 1958, 1986, 3229,
       3250, 3238, 3291, 3312, 3302, 3253, 3228, 3172, 3292, 3268, 3282,
       3303, 3257, 3411, 3389, 3345, 3418, 3363, 3365, 3348, 3485, 3502,
       3496, 3467, 3459, 3525, 3425, 3477, 3425, 3454, 3382, 3393, 3360,
       3317, 3337, 3329, 3327, 3542, 3537, 3607, 35

In [19]:
#y indices
pixels_y

array([5057, 5097, 4966, 4894, 5008, 5038, 5160, 5607, 5738, 5855, 5928,
       5708, 5864, 5907, 5681, 5618, 5832, 4965, 5490, 5602, 5465, 4942,
       4990, 4675, 4652, 4997, 5528, 5457, 5787, 5791, 7175, 7123, 7303,
       7374, 7314, 7544, 7203, 7263, 7479, 7124, 7731, 7745, 7909, 7699,
       7933, 6269, 6405, 5112, 1377, 1025,  978, 1279, 1359, 1431, 1249,
       5010, 5711, 5974, 6398, 6752, 2348, 2123, 2839, 2860, 5973, 5974,
       5967, 5970, 5966, 5767, 5961, 6146, 6043, 5910, 5840, 4955, 5590,
       5718, 5361, 5538, 5434, 5049, 4701, 4992, 4452, 4898, 5011, 5086,
       5014, 5023, 5059, 5166, 5181, 5224, 5319, 4935, 4887, 5272, 5528,
       5876, 5635, 5952, 5916, 5894, 6178, 6056, 6178, 5930, 5941, 7079,
       7165, 7211, 7210, 7288, 7117, 6979, 6952, 7041, 7394, 7345, 7336,
       7420, 7446, 7401, 7304, 7381, 7524, 7545, 7491, 7429, 7594, 7478,
       7461, 7430, 7352, 7275, 7655, 7717, 7699, 7696, 7634, 7598, 7618,
       7616, 7575, 7484, 7526, 7432, 7507, 7392, 73

In [22]:
classes = img_plots_points['class']
classes = np.array(classes)

In [23]:
classes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2])