In [1]:
import numpy as np
from osgeo import gdal, gdal_array
import pandas as pd
import operator
import gc
import os

In [2]:
x = gdal.Open("10_2019.tif", gdal.GA_ReadOnly)
print(x)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD6639F0> >


In [3]:
images = ["10_2019.tif", "11_2019.tif", "12_2019.tif", 
          "01_2020.tif", "02_2020.tif", "03_2020.tif"]

In [4]:
d_1 = gdal.Open("10_2019.tif", gdal.GA_ReadOnly)
print(d_1)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD663780> >


In [5]:
d_2 = gdal.Open("11_2019.tif", gdal.GA_ReadOnly)
print(d_2)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD663AE0> >


In [6]:
d_3 = gdal.Open("12_2019.tif", gdal.GA_ReadOnly)
print(d_3)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD663810> >


In [7]:
d_4 = gdal.Open("01_2020.tif", gdal.GA_ReadOnly)
print(d_4)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259ABEBAA20> >


In [8]:
d_5 = gdal.Open("02_2020.tif", gdal.GA_ReadOnly)
print(d_5)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD663900> >


In [9]:
d_6 = gdal.Open("03_2020.tif", gdal.GA_ReadOnly)
print(d_6)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259ABEBAA80> >


In [10]:
print(d_1, d_2, d_3, d_4, d_5,d_6)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD663780> > <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD663AE0> > <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD663810> > <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259ABEBAA20> > <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259AD663900> > <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000259ABEBAA80> >


In [25]:
dir(d_1)

['AddBand',
 'AdviseRead',
 'BeginAsyncReader',
 'BuildOverviews',
 'CommitTransaction',
 'CopyLayer',
 'CreateLayer',
 'CreateMaskBand',
 'DeleteLayer',
 'EndAsyncReader',
 'ExecuteSQL',
 'FlushCache',
 'GetDescription',
 'GetDriver',
 'GetFileList',
 'GetGCPCount',
 'GetGCPProjection',
 'GetGCPSpatialRef',
 'GetGCPs',
 'GetGeoTransform',
 'GetLayer',
 'GetLayerByIndex',
 'GetLayerByName',
 'GetLayerCount',
 'GetMetadata',
 'GetMetadataDomainList',
 'GetMetadataItem',
 'GetMetadata_Dict',
 'GetMetadata_List',
 'GetNextFeature',
 'GetProjection',
 'GetProjectionRef',
 'GetRasterBand',
 'GetSpatialRef',
 'GetStyleTable',
 'GetSubDatasets',
 'GetTiledVirtualMem',
 'GetTiledVirtualMemArray',
 'GetVirtualMem',
 'GetVirtualMemArray',
 'RasterCount',
 'RasterXSize',
 'RasterYSize',
 'ReadAsArray',
 'ReadRaster',
 'ReadRaster1',
 'ReleaseResultSet',
 'ResetReading',
 'RollbackTransaction',
 'SetDescription',
 'SetGCPs',
 'SetGeoTransform',
 'SetMetadata',
 'SetMetadataItem',
 'SetProjection',

In [26]:
d_1.RasterCount

5

In [27]:
d_1.GetDescription()

'10_2019.tif'

In [28]:
d_1.RasterXSize

8298

In [29]:
d_1.RasterYSize

8963

In [30]:
d_1.GetGeoTransform()

(74.62179301041088,
 8.983152841195215e-05,
 0.0,
 30.582155701036577,
 0.0,
 -8.983152841195215e-05)

In [32]:
d_1.GetProjection

<bound method Dataset.GetProjection of <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x0000016844E75BA0> >>

In [34]:
d_1.GetMetadata()

{'AREA_OR_POINT': 'Area'}

In [11]:
d1 = np.array(d_1.GetRasterBand(1).ReadAsArray())

In [12]:
print(d1)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [15]:
total = np.sum(np.unique(d1))

In [17]:
total

nan

In [18]:
np.unique(d1)

array([1006., 1016., 1018., ...,   nan,   nan,   nan])

In [19]:
d1.shape

(8963, 8298)

In [20]:
d1.ndim

2

In [21]:
d2 = np.array(d_2.GetRasterBand(1).ReadAsArray())

In [31]:
d2

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [23]:
np.unique(d2)

array([1004. , 1005.5, 1006.5, ...,    nan,    nan,    nan])

In [24]:
d3 = np.array(d_3.GetRasterBand(1).ReadAsArray())
d4 = np.array(d_4.GetRasterBand(1).ReadAsArray())
d5 = np.array(d_5.GetRasterBand(1).ReadAsArray())
d6 = np.array(d_6.GetRasterBand(1).ReadAsArray())

In [30]:
d3.shape

(8963, 8298)