In [1]:
import numpy as np

In [2]:
a = np.array([[5.8, 2.8], [6.0, 2.2]])

In [3]:
a.shape

(2, 2)

In [4]:
a

array([[5.8, 2.8],
       [6. , 2.2]])

In [6]:
a = a.reshape((2*2, 1))

In [7]:
a

array([[5.8],
       [2.8],
       [6. ],
       [2.2]])

In [8]:
a= a.reshape((2,2))
a

array([[5.8, 2.8],
       [6. , 2.2]])