In [8]:
import numpy as np
import os
import pandas as pd

In [9]:
from skimage import io

In [10]:
from skimage.io import imread

In [11]:
dir = "E:\\Internship_Harvesting\\Dataset"
print(dir)

E:\Internship_Harvesting\Dataset


In [12]:
listfiles =[]
print(listfiles)

[]


In [13]:
print(os.listdir(dir))

['01_2020.tif', '02_2020.tif', '03_2020.tif', '10_2019.tif', '11_2019.tif', '12_2019.tif', 'Bathinda', 'Split Images', 'Stack Image']


In [14]:
for img_files in os.listdir(dir):
    print(img_files)

01_2020.tif
02_2020.tif
03_2020.tif
10_2019.tif
11_2019.tif
12_2019.tif
Bathinda
Split Images
Stack Image


In [15]:
for img_files in os.listdir(dir):
    if img_files.endswith(".tif"):
        listfiles.append(img_files)

In [16]:
print(listfiles)

['01_2020.tif', '02_2020.tif', '03_2020.tif', '10_2019.tif', '11_2019.tif', '12_2019.tif']


In [17]:
first_image = io.imread("E:\\Internship_Harvesting\\Dataset\\10_2019.tif")

In [18]:
first_image

array([[[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]],

       [[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]],

       [[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]],

       ...,

       [[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]],

       [[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan

In [19]:
first_image.size

371874870

In [20]:
first_image.ndim

3

In [21]:
first_image.shape

(8963, 8298, 5)

In [22]:
type(first_image)

numpy.ndarray

In [23]:
np.unique(first_image)

array([577., 582., 583., ...,  nan,  nan,  nan])

In [28]:
stack = np.zeros((6, first_image.shape[0], first_image.shape[1], first_image.shape[2]), np.uint8)

In [29]:
print(stack)

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  ...

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  ...

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0

In [30]:
stack.shape

(6, 8963, 8298, 5)

In [31]:
stack.ndim

4

In [32]:
for n in range(0,6):
    stack[n,:,:,:]= io.imread(dir+"\\"+listfiles[n])

In [33]:
print(stack)

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  ...

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  ...

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0

In [34]:
stack.ndim

4

In [35]:
stack.size

2231249220

In [36]:
stack.shape

(6, 8963, 8298, 5)

In [37]:
type(stack)

numpy.ndarray

In [38]:
np.unique(stack)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [39]:
np.sum(np.unique(stack))

32640

In [40]:
#  path_results = 'C:/Users/Mich/Desktop/'

path_results = 'E:\\Internship_Harvesting\\Dataset\\'

In [35]:
io.imsave(path_results+'Stacked.tif' ,stack)