In [0]:
import numpy as np
import matplotlib.pyplot as plt
import h5py

In [0]:
import pandas as pd

In [0]:
import scipy
from PIL import Image
from scipy import ndimage

In [4]:
pip install geopandas

In [0]:
import gdal
import os
import geopandas as gpd
from skimage import io
from skimage.io import imread
%matplotlib inline

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
del test_y, test_x, train_x, train_y, cv_x, cv_y

In [0]:
del data, train, train_1,sample_test
del array_nan, nan_index, x_nan, sample

In [60]:
# reading the training data

data = pd.read_csv("/content/gdrive/My Drive/Harvesting/train.csv")
data.drop(data.columns[0], axis = 1, inplace = True)
data

Image6band5  Image6band4  Image6band3  ...  Image1band2  Image1band1  class
0         3426.0        869.0        573.5  ...         1209       1208.0      1
1         3304.0        937.5        600.5  ...         1195       1191.0      1
2         3096.0        891.5        595.5  ...         1258       1216.0      1
3         3634.0        929.5        574.0  ...         1120       1175.0      1
4         3329.5        846.5        560.5  ...         1243       1197.0      1
..           ...          ...          ...  ...          ...          ...    ...
156       2019.5       1378.0       1242.5  ...         1218       1221.0      2
157       3102.5       1002.5        691.0  ...         1574       1559.0      2
158       2529.0       1846.5       1792.5  ...         1676       1575.0      2
159       2071.0       1186.0        936.5  ...         1296       1350.0      2
160       2011.5       1218.5       1024.0  ...         1527       1506.0      2

[161 rows x 31 columns]

In [0]:
train = data.to_numpy()

In [0]:
import numpy as np
from sklearn.model_selection import train_test_split

In [0]:
cv_size = 20/80

train_1, cv = train_test_split(train, test_size = cv_size)

In [64]:
train_x = train_1[:, :30]
train_y = train_1[:, 30:]

cv_x = cv[:, :30]
cv_y = cv[:, 30:]

train_x.shape, train_y.shape, cv_x.shape, cv_y.shape

((120, 30), (120, 1), (41, 30), (41, 1))

In [0]:
train_y = train_y.astype("int")
cv_y = cv_y.astype("int")

In [66]:
train_x.shape, train_y.shape, cv_x.shape, cv_y.shape

((120, 30), (120, 1), (41, 30), (41, 1))

In [67]:
train_x = train_x.T
train_y = train_y.T

cv_x = cv_x.T
cv_y = cv_y.T

train_x.shape, train_y.shape, cv_x.shape, cv_y.shape

((30, 120), (1, 120), (30, 41), (1, 41))

In [0]:
cv_y[cv_y[:] == 1] = 0

In [0]:
cv_y[cv_y[:] == 2] = 1

In [0]:
train_y[train_y[:] == 1] = 0

In [0]:
train_y[train_y[:] == 2] = 1

In [0]:
# reading the csv file which has the labeled indices..

labeled_indices = pd.read_csv("/content/gdrive/My Drive/Harvesting/labeled_index.csv")

labeled_indices.drop(labeled_indices.columns[0], axis = 1, inplace = True)

In [0]:
img = ["/content/gdrive/My Drive/Harvesting/1.tif",
      "/content/gdrive/My Drive/Harvesting/2.tif",
      "/content/gdrive/My Drive/Harvesting/3.tif",
      "/content/gdrive/My Drive/Harvesting/4.tif",
      "/content/gdrive/My Drive/Harvesting/5.tif",
      "/content/gdrive/My Drive/Harvesting/6.tif"]

In [74]:
sample_test = np.zeros((2766*2988, 1))
sample_test.shape

(8264808, 1)

In [75]:
for i in img:
    image = gdal.Open(i)
    print(image)
    
    image_zero = np.zeros((image.RasterYSize, image.RasterXSize, image.RasterCount))
    
    for b in range(image_zero.shape[2]):
        image_zero[:, :, b] = image.GetRasterBand(b + 1).ReadAsArray()
        
        for a in range(len(labeled_indices["x_index"].values)):
            image_zero[:,:,b].T[labeled_indices.iloc[a,0], labeled_indices.iloc[a,1]] = 0
            
        sample = image_zero[:,:,b].T[:2766, :2988]
        print(sample.shape)
        sample = sample.reshape((2766*2988, 1))
        print(sample.shape)
        
        sample_test = np.concatenate((sample, sample_test), axis = 1)
        
sample_test

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f41fbef5fc0> >
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f41fbef5750> >
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f41fbef5fc0> >
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f41fbef5750> >
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
(2766, 2988)
(8264808, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f41fbef5fc0> >
(2766, 298

array([[   nan,    nan,    nan, ...,    nan,    nan,    0. ],
       [   nan,    nan,    nan, ...,    nan,    nan,    0. ],
       [   nan,    nan,    nan, ...,    nan,    nan,    0. ],
       ...,
       [3147. , 1325. ,  846. , ..., 1232. , 1277. ,    0. ],
       [3501. , 1024.5,  733.5, ..., 1219. , 1258. ,    0. ],
       [3488.5, 1024.5,  717.5, ..., 1246. , 1278. ,    0. ]])

In [76]:
sample_test.shape

(8264808, 31)

In [77]:
sample_test = sample_test[:, :30]
sample_test.shape

(8264808, 30)

In [78]:
np.count_nonzero(np.isnan(sample_test[:, 1]))

7361064

In [79]:
np.count_nonzero(np.isnan(sample_test[:, 2]))

7361064

In [80]:
np.count_nonzero(np.isnan(sample_test))

220831920

In [81]:
array_nan = sample_test[:, 1]
array_nan.shape

(8264808,)

In [82]:
array_nan = array_nan.reshape((2766, 2988))
array_nan.shape

(2766, 2988)

In [0]:
nan_index = np.argwhere(np.isnan(array_nan))

In [84]:
nan_index

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [2765, 2161],
       [2765, 2162],
       [2765, 2163]])

In [85]:
nan_index.shape

(7361064, 2)

In [0]:
test = sample_test.T

In [87]:
test.shape

(30, 8264808)

In [0]:
test_x = test

In [89]:
train_x.shape

(30, 120)

In [0]:
for i in range(train_x.shape[0]):
    a = np.mean(train_x[i, :])
    b = np.std(train_x[i, :])
    #print(train_x[i, :])
    #print(a," : ", b ,"\n")
    train_x[i, :] = (train_x[i, :] - a) / b
    cv_x[i, :] = (cv_x[i, :] - a) / b
    test_x[i, :] = (test_x[i, :] - a) / b

In [0]:
# GRADED FUNCTION: sigmoid

def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    z -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1/(1 + np.exp(-z))
    ### END CODE HERE ###
    
    return s

In [0]:
# GRADED FUNCTION: initialize_with_zeros

def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    w = np.zeros((dim, 1))
    b = 0
    ### END CODE HERE ###

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b

In [0]:
# GRADED FUNCTION: propagate

def propagate(w, b, X, Y):
    """
    Implement the cost function and its gradient for the propagation explained above

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    ### START CODE HERE ### (≈ 2 lines of code)
    A = sigmoid(np.dot(w.T, X) + b)                                           # compute activation
    cost = -1 / m * np.sum(Y * np.log(A) + (1-Y) * np.log(1-A))                                 # compute cost
    ### END CODE HERE ###
    
    # BACKWARD PROPAGATION (TO FIND GRAD)
    ### START CODE HERE ### (≈ 2 lines of code)
    dw = (1/m)*np.dot(X, (A-Y).T)
    db = (1/m)*np.sum((A - Y))
    ### END CODE HERE ###

    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [0]:
# GRADED FUNCTION: optimize

def optimize(w, b, X, Y, num_iterations, learning_rate, print_cost = False):
    """
    This function optimizes w and b by running a gradient descent algorithm
    
    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of shape (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat), of shape (1, number of examples)
    num_iterations -- number of iterations of the optimization loop
    learning_rate -- learning rate of the gradient descent update rule
    print_cost -- True to print the loss every 100 steps
    
    Returns:
    params -- dictionary containing the weights w and bias b
    grads -- dictionary containing the gradients of the weights and bias with respect to the cost function
    costs -- list of all the costs computed during the optimization, this will be used to plot the learning curve.
    
    Tips:
    You basically need to write down two steps and iterate through them:
        1) Calculate the cost and the gradient for the current parameters. Use propagate().
        2) Update the parameters using gradient descent rule for w and b.
    """
    
    costs = []
    
    for i in range(num_iterations):
        
        
        # Cost and gradient calculation (≈ 1-4 lines of code)
        ### START CODE HERE ### 
        grads, cost = propagate(w, b, X, Y)
        ### END CODE HERE ###
        
        # Retrieve derivatives from grads
        dw = grads["dw"]
        db = grads["db"]
        
        # update rule (≈ 2 lines of code)
        ### START CODE HERE ###
        w = w - learning_rate*dw
        b = b - learning_rate*db
        ### END CODE HERE ###
        
        # Record the costs
        if i % 100 == 0:
            costs.append(cost)
        
        # Print the cost every 100 training iterations
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
    
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}
    
    return params, grads, costs

In [0]:
# GRADED FUNCTION: predict

def predict(w, b, X):
    '''
    Predict whether the label is 0 or 1 using learned logistic regression parameters (w, b)
    
    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    
    Returns:
    Y_prediction -- a numpy array (vector) containing all predictions (0/1) for the examples in X
    '''
    
    m = X.shape[1]
    Y_prediction = np.zeros((1,m))
    w = w.reshape(X.shape[0], 1)
    
    # Compute vector "A" predicting the probabilities of a cat being present in the picture
    ### START CODE HERE ### (≈ 1 line of code)
    A = sigmoid(np.dot(w.T, X) + b)
    ### END CODE HERE ###
    
    for i in range(A.shape[1]):
        
        # Convert probabilities A[0,i] to actual predictions p[0,i]
        ### START CODE HERE ### (≈ 4 lines of code)
        if A[0, i] > 0.5:
            Y_prediction[0, i] = 1
        else:
            Y_prediction[0, i] = 0
        ### END CODE HERE ###
    
    assert(Y_prediction.shape == (1, m))
    
    return Y_prediction

In [0]:
# GRADED FUNCTION: model

def model(X_train, Y_train, X_test, Y_test, num_iterations = 2000, learning_rate = 0.5, print_cost = False):
    """
    Builds the logistic regression model by calling the function you've implemented previously
    
    Arguments:
    X_train -- training set represented by a numpy array of shape (num_px * num_px * 3, m_train)
    Y_train -- training labels represented by a numpy array (vector) of shape (1, m_train)
    X_test -- test set represented by a numpy array of shape (num_px * num_px * 3, m_test)
    Y_test -- test labels represented by a numpy array (vector) of shape (1, m_test)
    num_iterations -- hyperparameter representing the number of iterations to optimize the parameters
    learning_rate -- hyperparameter representing the learning rate used in the update rule of optimize()
    print_cost -- Set to true to print the cost every 100 iterations
    
    Returns:
    d -- dictionary containing information about the model.
    """
    
    ### START CODE HERE ###
    
    # initialize parameters with zeros (≈ 1 line of code)
    w, b = initialize_with_zeros(X_train.shape[0])

    # Gradient descent (≈ 1 line of code)
    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost)
    
    # Retrieve parameters w and b from dictionary "parameters"
    w = parameters["w"]
    b = parameters["b"]
    
    # Predict test/train set examples (≈ 2 lines of code)
    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)

    ### END CODE HERE ###

    # Print train/test Errors
    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
    print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

    
    d = {"costs": costs,
         "Y_prediction_test": Y_prediction_test, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d

In [97]:
# d = model(train_set_x, train_set_y, test_set_x, test_set_y, num_iterations = 2000, learning_rate = 0.005, print_cost = True)

a = model(train_x, train_y, cv_x, cv_y, num_iterations = 2000, learning_rate = 0.005, print_cost = True)

Cost after iteration 0: 0.693147
Cost after iteration 100: 0.242041
Cost after iteration 200: 0.149701
Cost after iteration 300: 0.110390
Cost after iteration 400: 0.088393
Cost after iteration 500: 0.074210
Cost after iteration 600: 0.064238
Cost after iteration 700: 0.056807
Cost after iteration 800: 0.051033
Cost after iteration 900: 0.046404
Cost after iteration 1000: 0.042601
Cost after iteration 1100: 0.039416
Cost after iteration 1200: 0.036704
Cost after iteration 1300: 0.034365
Cost after iteration 1400: 0.032325
Cost after iteration 1500: 0.030528
Cost after iteration 1600: 0.028932
Cost after iteration 1700: 0.027505
Cost after iteration 1800: 0.026219
Cost after iteration 1900: 0.025056
train accuracy: 100.0 %
test accuracy: 100.0 %


In [98]:
for i in a:
    print("\n\n", i,"  :::  ", a[i])



 costs   :::   [0.6931471805599453, 0.24204062910745025, 0.1497007636828668, 0.11039018555600004, 0.08839306086903333, 0.07420975933447342, 0.06423793353192027, 0.05680687666143268, 0.05103313178871622, 0.04640415923116485, 0.04260132650806026, 0.039415646325057715, 0.036704059409791094, 0.03436515829363774, 0.03232494326862626, 0.03052807473808281, 0.028932290749436984, 0.02750472570265272, 0.026219413021777393, 0.025055548612381757]


 Y_prediction_test   :::   [[1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1.
  1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0.]]


 Y_prediction_train   :::   [[0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.
  0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0.
  0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0.
  1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1.]]

In [0]:
test_y = predict(a["w"], a["b"], test_x)

In [100]:
test_y.shape

(1, 8264808)

In [0]:
test_y = test_y.T

In [0]:
test_y = test_y.reshape((2766, 2988))

In [103]:
test_y.shape

(2766, 2988)

In [0]:
x_nan = test_y.copy()

In [105]:
x_nan.shape

(2766, 2988)

In [0]:
for i in range(nan_index.shape[0]):
  x_nan[nan_index[i,0], nan_index[i,1]] = 128

In [107]:
x_nan

array([[128., 128., 128., ..., 128., 128., 128.],
       [128., 128., 128., ..., 128., 128., 128.],
       [128., 128., 128., ..., 128., 128., 128.],
       ...,
       [128., 128., 128., ...,   1.,   0.,   0.],
       [128., 128., 128., ...,   1.,   1.,   0.],
       [128., 128., 128., ...,   1.,   0.,   0.]])

In [108]:
test_y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [109]:
x_nan[x_nan == 1] = 255
x_nan

array([[128., 128., 128., ..., 128., 128., 128.],
       [128., 128., 128., ..., 128., 128., 128.],
       [128., 128., 128., ..., 128., 128., 128.],
       ...,
       [128., 128., 128., ..., 255.,   0.,   0.],
       [128., 128., 128., ..., 255., 255.,   0.],
       [128., 128., 128., ..., 255.,   0.,   0.]])

In [110]:
x_nan = x_nan.astype("uint8")
x_nan

array([[128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128],
       ...,
       [128, 128, 128, ..., 255,   0,   0],
       [128, 128, 128, ..., 255, 255,   0],
       [128, 128, 128, ..., 255,   0,   0]], dtype=uint8)

In [111]:
np.unique(x_nan)

array([  0, 128, 255], dtype=uint8)

In [0]:
import numpy as np
import os
import pandas as pd
from skimage import io
from skimage.io import imread

In [0]:
io.imsave("/content/gdrive/My Drive/Harvesting/test_1.jpg" ,x_nan)

In [114]:
import gc
gc.collect()

224