In [2]:
import numpy as np
import os
import pandas as pd

In [3]:
from skimage import io

In [4]:
from skimage.io import imread

In [5]:
stack = io.imread("E:\\Internship_Harvesting\\Dataset\\Stacked.tif")

In [6]:
print(stack)

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  ...

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  ...

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   ...
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0

In [7]:
stack.size

2231249220

In [8]:
stack.shape

(6, 8963, 8298, 5)

In [10]:
stack.ndim

4

In [11]:
np.sum(np.unique(stack))

32640

In [12]:
np.unique(stack)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [13]:
# now as the image size is 6*8963*8298*5,
# in which 1st dimension is time dimension
# 2nd is X-axis no of pixels
# 3rd is y-axis no. of pixels
# 4th is no. of bands

# so splitting the stacked image in 30 smaller images
# by breaking the x and y pixels,
# small images will have dimensions,
# 6*1494*1660*5 each (30 images)

In [75]:
split_1 = stack[:,0:1494,0:1660,:]

In [76]:
split_1.shape

(6, 1494, 1660, 5)

In [77]:
split_1.size

74401200

In [78]:
split_1.ndim

4

In [79]:
type(split_1)

numpy.ndarray

In [19]:
# stack[:, i*1494:(1*1494+1493), j*1660:(j*1660+1659), :]

In [102]:
s = np.zeros((6,5))

In [103]:
for i in range(0,6):
    for j in range(0,5):
        s.append(stack[:, i*1494:(1*1494+1493), j*1660:(j*1660+1659), :])
        print(s[i, j])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [60]:
split_1

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         ...,
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         ...,
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         ...,
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        ...,

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         ...,
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         ...,
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         ...,
         [0, 0, 0, 0, 0],
        

In [81]:
split_2 = stack[:, 1494:2988, 0:1660, :]
split_2.shape

(6, 1494, 1660, 5)

In [82]:
split_3 = stack[:, 2988:4482, 0:1660, :]
split_3.shape

(6, 1494, 1660, 5)

In [83]:
split_4 = stack[:, 4482:5976, 0:1660, :]
split_4.shape

(6, 1494, 1660, 5)

In [84]:
split_5 = stack[:, 5976:7470, 0:1660, :]
split_5.shape

(6, 1494, 1660, 5)

In [85]:
split_6 = stack[:, 7470:8964, 0:1660, :]
split_6.shape

(6, 1493, 1660, 5)

In [86]:
split_7 = stack[:, 0:1494, 1660:3320, :]
split_7.shape

(6, 1494, 1660, 5)

In [87]:
split_13 = stack[:, 0:1494, 3320:4980, :]
split_13.shape

(6, 1494, 1660, 5)

In [88]:
split_19 = stack[:, 0:1494, 4980:6640, :]
split_19.shape

(6, 1494, 1660, 5)

In [89]:
split_25 = stack[:, 0:1494, 6640:8300, :]
split_25.shape

(6, 1494, 1658, 5)

In [90]:
path_results = 'E:\\Internship_Harvesting\\Dataset\\'

In [91]:
io.imsave(path_results+'split_1.tif' ,split_1)

C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: E:\Internship_Harvesting\Dataset\split_1.tif is a low contrast image
  """Entry point for launching an IPython kernel.


In [93]:
split_8 = stack[:, 1494:2988, 1660:3320, :]
split_8.shape

(6, 1494, 1660, 5)

In [94]:
split_9 = stack[:, 2988:4482, 1660:3320, :]
split_9.shape

(6, 1494, 1660, 5)

In [95]:
split_10 = stack[:, 4482:5976, 1660:3320, :]
split_10.shape

(6, 1494, 1660, 5)

In [96]:
split_11 = stack[:, 5976:7470, 1660:3320, :]
split_11.shape

(6, 1494, 1660, 5)

In [113]:
split_12 = stack[:, 7470:8964, 1660:3320, :]
split_12.shape

(6, 1493, 1660, 5)

In [104]:
split_14 = stack[:, 1494:2988, 3320:4980, :]
print(split_14.shape)

split_15 = stack[:, 2988:4482, 3320:4980, :]
print("\n", split_15.shape)

split_16 = stack[:, 4482:5976, 3320:4980, :]
print("\n", split_16.shape)

split_17 = stack[:, 5976:7470, 3320:4980, :]
print("\n", split_17.shape)

split_18 = stack[:, 7470:8964, 3320:4980, :]
print("\n", split_18.shape)

(6, 1494, 1660, 5)

 (6, 1494, 1660, 5)

 (6, 1494, 1660, 5)

 (6, 1494, 1660, 5)

 (6, 1493, 1660, 5)


In [105]:
split_20 = stack[:, 1494:2988, 4980:6640, :]
print(split_20.shape)

split_21 = stack[:, 2988:4482, 4980:6640, :]
print("\n", split_21.shape)

split_22 = stack[:, 4482:5976, 4980:6640, :]
print("\n", split_22.shape)

split_23 = stack[:, 5976:7470, 4980:6640, :]
print("\n", split_23.shape)

split_24 = stack[:, 7470:8964, 4980:6640, :]
print("\n", split_24.shape)

(6, 1494, 1660, 5)

 (6, 1494, 1660, 5)

 (6, 1494, 1660, 5)

 (6, 1494, 1660, 5)

 (6, 1493, 1660, 5)


In [106]:
split_26 = stack[:, 1494:2988, 6640:8300, :]
print(split_26.shape)

split_27 = stack[:, 2988:4482, 6640:8300, :]
print("\n", split_27.shape)

split_28 = stack[:, 4482:5976, 6640:8300, :]
print("\n", split_28.shape)

split_29 = stack[:, 5976:7470, 6640:8300, :]
print("\n", split_29.shape)

split_30 = stack[:, 7470:8964, 6640:8300, :]
print("\n", split_30.shape)

(6, 1494, 1658, 5)

 (6, 1494, 1658, 5)

 (6, 1494, 1658, 5)

 (6, 1494, 1658, 5)

 (6, 1493, 1658, 5)


In [110]:
io.imsave(path_results+'split_2.tif' ,split_2)

In [111]:
io.imsave(path_results+'split_3.tif' ,split_3)
io.imsave(path_results+'split_4.tif' ,split_4)
io.imsave(path_results+'split_5.tif' ,split_5)
io.imsave(path_results+'split_6.tif' ,split_6)
io.imsave(path_results+'split_7.tif' ,split_7)
io.imsave(path_results+'split_8.tif' ,split_8)
io.imsave(path_results+'split_9.tif' ,split_9)
io.imsave(path_results+'split_10.tif' ,split_10)


C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: E:\Internship_Harvesting\Dataset\split_6.tif is a low contrast image
  after removing the cwd from sys.path.
C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: E:\Internship_Harvesting\Dataset\split_7.tif is a low contrast image
  """


In [114]:
io.imsave(path_results+'split_11.tif' ,split_11)
io.imsave(path_results+'split_12.tif' ,split_12)
io.imsave(path_results+'split_13.tif' ,split_13)
io.imsave(path_results+'split_14.tif' ,split_14)
io.imsave(path_results+'split_15.tif' ,split_15)
io.imsave(path_results+'split_16.tif' ,split_16)
io.imsave(path_results+'split_17.tif' ,split_17)
io.imsave(path_results+'split_18.tif' ,split_18)
io.imsave(path_results+'split_19.tif' ,split_19)
io.imsave(path_results+'split_20.tif' ,split_20)

C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: E:\Internship_Harvesting\Dataset\split_12.tif is a low contrast image
  


In [115]:
io.imsave(path_results+'split_21.tif' ,split_21)
io.imsave(path_results+'split_22.tif' ,split_22)
io.imsave(path_results+'split_23.tif' ,split_23)
io.imsave(path_results+'split_24.tif' ,split_24)
io.imsave(path_results+'split_25.tif' ,split_25)
io.imsave(path_results+'split_26.tif' ,split_26)
io.imsave(path_results+'split_27.tif' ,split_27)
io.imsave(path_results+'split_28.tif' ,split_28)
io.imsave(path_results+'split_29.tif' ,split_29)
io.imsave(path_results+'split_30.tif' ,split_30)

C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: E:\Internship_Harvesting\Dataset\split_30.tif is a low contrast image
  # Remove the CWD from sys.path while we load stuff.
